name: Build and Test plugin
on:
  push:
    branches:
      - "*"
      - "feature/**"
  pull_request:
    branches:
      - "*"
      - "feature/**"
jobs:
  Get-CI-Image-Tag:
    uses: opensearch-project/opensearch-build/.github/workflows/get-ci-image-tag.yml@main
    with:
      product: opensearch

  Build-linux:
    needs: Get-CI-Image-Tag
    strategy:
      matrix:
        java: [21, 25]

    name: Build and Test geospatial Plugin
    runs-on: ubuntu-latest
    container:
      # using the same image which is used by opensearch-build team to build the OpenSearch Distribution
      # this image tag is subject to change as more dependencies and updates will arrive over time
      image: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-version-linux }}
      options: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-options }}

    steps:
      - name: Run start commands
        run: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-command }}

      - name: Checkout geospatial
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Run build
        run: |
          chown -R 1000:1000 `pwd`
          su `id -un 1000` -c "./gradlew build"

      - name: Upload Coverage Report Artifact
        if: ${{ !cancelled() && matrix.java == 21 }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: jacoco-coverage-report
          path: build/reports/jacoco/test/jacocoTestReport.xml
          retention-days: 1
          if-no-files-found: error

  Upload-Coverage:
    needs: Build-linux
    name: Upload Coverage Report to Codecov
    if: ${{ !cancelled() && github.repository == 'opensearch-project/geospatial' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout geospatial
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Download Coverage Report
        id: download-coverage
        continue-on-error: true
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: jacoco-coverage-report
          path: build/reports/jacoco/test

      - name: Upload Coverage Report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        if: steps.download-coverage.outcome == 'success'
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  Build-windows-macos:
    strategy:
      matrix:
        java: [21, 25]
        os: [windows-latest, macos-latest]

    name: Build and Test geospatial Plugin
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout geospatial
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Run build
        run: |
          ./gradlew build

      - name: Upload Coverage Report
        if: ${{ !cancelled() && github.repository == 'opensearch-project/geospatial' }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.CODECOV_TOKEN }}
